#!/usr/bin/env python3
import os
import sys
import glob
import polib

def collect_po_files(po_dir):
    return sorted(glob.glob(os.path.join(po_dir, "*.po")))

def load_po_entries(po_path):
    po = polib.pofile(po_path)
    entries = []
    for entry in po:
        if entry.msgid:
            msgstr = entry.msgstr if entry.msgstr else ""
            entries.append((entry.msgid, msgstr))
    return entries

def escape_utf16(s):
    """
    Convert Python Unicode string → UTF-16 escape sequence for C (u"…")
    Example: "あ" → "\\u3042"
    """
    out = []
    for ch in s:
        code = ord(ch)
        if code <= 0xFFFF:
            out.append(f"\\u{code:04X}")
        else:
            # surrogate pair
            code -= 0x10000
            high = 0xD800 + (code >> 10)
            low  = 0xDC00 + (code & 0x3FF)
            out.append(f"\\u{high:04X}\\u{low:04X}")
    return "".join(out)

def generate_c(po_dir, output_c):
    po_files = collect_po_files(po_dir)
    if not po_files:
        print(f"No .po files found in {po_dir}")
        sys.exit(1)

    base_entries = load_po_entries(po_files[0])
    msgids = [msgid for msgid, _ in base_entries]

    translations = {}
    for po_path in po_files:
        lang = os.path.splitext(os.path.basename(po_path))[0]
        entries = load_po_entries(po_path)

        msgid_to_msgstr = {msgid: msgstr for msgid, msgstr in entries}
        msgstr_list = [msgid_to_msgstr.get(msgid, "") for msgid in msgids]

        translations[lang] = msgstr_list

    with open(output_c, "w", encoding="utf-8") as f:
        f.write("// Auto-generated translation table (C version)\n")
        f.write("// Do not edit this file manually.\n\n")
        f.write("#include <inttypes.h>\n")
        f.write("#include <string.h>\n")
        f.write("#include <uchar.h>\n")
        f.write("#include \"translate.h\"\n\n")

        # msgid table
        f.write("// List of all msgid strings\n")
        f.write("static const char16_t* msgid_table[] = {\n")
        for msgid in msgids:
            esc = escape_utf16(msgid)
            f.write(f"    u\"{esc}\",\n")
        f.write("    NULL\n};\n\n")

        # msgstr tables
        for lang, msgstr_list in translations.items():
            f.write(f"// Translations for language: {lang}\n")
            f.write(f"static const char16_t* msgstr_{lang}[] = {{\n")
            for msgstr in msgstr_list:
                esc = escape_utf16(msgstr)
                f.write(f"    u\"{esc}\",\n")
            f.write("    NULL\n};\n\n")

        # language table
        f.write("// Mapping of language code to translation table\n")
        f.write("typedef struct { const char* lang; const char16_t** table; } LangTable;\n")
        f.write("static const LangTable language_tables[] = {\n")
        for lang in translations.keys():
            f.write(f"    {{ \"{lang}\", msgstr_{lang} }},\n")
        f.write("    { NULL, NULL }\n};\n\n")

        # current language pointer
        f.write("// Pointer to the currently selected translation table\n")
        f.write("const char16_t** current_msgstr = NULL;\n\n")

        # SetLanguage()
        f.write("// Set the current language by language code\n")
        f.write("int SetLanguage(const char* lang)\n")
        f.write("{\n")
        f.write("    for (int i = 0; language_tables[i].lang != NULL; i++) {\n")
        f.write("        if (strcmp(language_tables[i].lang, lang) == 0) {\n")
        f.write("            current_msgstr = language_tables[i].table;\n")
        f.write("            return 0;\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("    return -1;\n")
        f.write("}\n\n")

        # lookup function
        f.write("// Translation lookup function\n")
        f.write("const char16_t* _(const char16_t* msgid)\n")
        f.write("{\n")
        f.write("    if (!current_msgstr)\n")
        f.write("        return msgid;\n\n")
        f.write("    for (int i = 0; msgid_table[i] != NULL; i++) {\n")
        f.write("        const char16_t* a = msgid_table[i];\n")
        f.write("        const char16_t* b = msgid;\n")
        f.write("\n")
        f.write("        while (*a && *b && *a == *b) {\n")
        f.write("            a++;\n")
        f.write("            b++;\n")
        f.write("        }\n")
        f.write("\n")
        f.write("        if (*a == u'\\0' && *b == u'\\0') {\n")
        f.write("            const char16_t* translated = current_msgstr[i];\n")
        f.write("            return (translated && translated[0]) ? translated : msgid;\n")
        f.write("        }\n")
        f.write("    }\n")
        f.write("    return msgid;\n")
        f.write("}\n")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: gen_translations.py <po_directory> <output_c>")
        sys.exit(1)

    generate_c(sys.argv[1], sys.argv[2])
